# Automate, customize, and execute your software development workflows right in your repository with GitHub Actions.
# Documentation: https://docs.github.com/en/actions

name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger build
      run: \
        curl --request POST \
        --form token=${{ secrets.CI_TOKEN }} \
        --form ref=${{ GITHUB_REF_NAME }} \
        ${{ secrets.CI_WEBHOOK_URL }}